apiVersion: apps/v1
kind: Deployment
metadata:
  name: iso8583backend
  labels:
    app: iso8583backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iso8583backend
  template:
    metadata:
      name: iso8583backend
      labels:
        app: iso8583backend
    spec:
      containers:
        - name: iso8583backend
          image: xenedium/iso8583backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: GRPC_ADDRESS
              value: iso8583parser:8080
      restartPolicy: Always
      