apiVersion: apps/v1
kind: Deployment
metadata:
  name: iso8583frontend
  labels:
    app: iso8583frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iso8583frontend
  template:
    metadata:
      name: iso8583frontend
      labels:
        app: iso8583frontend
    spec:
      containers:
        - name: iso8583frontend
          image: xenedium/iso8583frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: iso8583-configmap
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
      restartPolicy: Always
      