name: Update kubernetes manifests

on:
  push:
    tags:
      - 'v*.*.*'


jobs:
  update-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update the production kubernetes manifests if tagged
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          sed -i "s|xenedium/iso8583backend:\(.*\)|xenedium/iso8583backend:$REF_NAME|g" kubernetes/production/iso8583backend-deployment.yaml
          sed -i "s|xenedium/iso8583parser:\(.*\)|xenedium/iso8583parser:$REF_NAME|g" kubernetes/production/iso8583parser-deployment.yaml
          sed -i "s|xenedium/iso8583frontend:\(.*\)|xenedium/iso8583frontend:$REF_NAME|g" kubernetes/production/iso8583frontend-deployment.yaml

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.3
        with:
          push: 'origin main --force'
          add: kubernetes/production

